In [17]:
import os, sys
from pathlib import Path

cur_dir = os.getcwd()
path = Path(cur_dir)
sys.path.insert(0, str(path.parent.absolute()))

import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from src.preprocess import preprocess_df
from src.kalman_network_tools import parse_df_2_state_graphs

In [18]:
file_addr = '..\CIC-IDS-2017\GeneratedLabelledFlows\TrafficLabelling\Tuesday-WorkingHours.pcap_ISCX.csv'  # 'Monday-WorkingHours.pcap_ISCX.csv' #  Wednesday-workingHours.pcap_ISCX.csv
#file_addr = '..\CIC-IDS-2017\GeneratedLabelledFlows\TrafficLabelling\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv'
#file_addr = '..\CIC-IDS-2017\GeneratedLabelledFlows\TrafficLabelling\Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv'
#file_addr = '..\CIC-IDS-2017\GeneratedLabelledFlows\TrafficLabelling\Friday-WorkingHours-Morning.pcap_ISCX.csv'
#file_addr = '..\CIC-IDS-2017\GeneratedLabelledFlows\TrafficLabelling\Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv'
#file_addr = '..\CIC-IDS-2017\GeneratedLabelledFlows\TrafficLabelling\Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
df_cic = pd.read_csv(file_addr, header=0, encoding='cp1252')

df = preprocess_df(df_cic, date_col=' Timestamp')
print(df.shape)

(445645, 85)

In [19]:
with open(r'saves\connected_84.pickle', 'rb') as handle:
    names = pickle.load(handle) 

len(names)

84

Graphs as Input

In [4]:


all_graphs, labels, label_counts, _ = parse_df_2_state_graphs(df, entity_names=names, t_graph=20, sync_window_size=0.5, skip_idle=True,
                                                              return_datetimes=False, timeit=False )

1
Current time and samples shape:  2017-04-07 01:01:00 (40, 84)
2
Current time and samples shape:  2017-04-07 01:02:00 (40, 84)
3
Current time and samples shape:  2017-04-07 01:03:00 (40, 84)
4
Current time and samples shape:  2017-04-07 01:04:00 (40, 84)
5
Current time and samples shape:  2017-04-07 01:05:00 (40, 84)
6
Current time and samples shape:  2017-04-07 01:06:00 (40, 84)
7
Current time and samples shape:  2017-04-07 01:07:00 (40, 84)
8
Current time and samples shape:  2017-04-07 01:08:00 (40, 84)
9
Current time and samples shape:  2017-04-07 01:09:00 (40, 84)
10
Current time and samples shape:  2017-04-07 01:10:00 (40, 84)
11
Current time and samples shape:  2017-04-07 01:11:00 (40, 84)
12
Current time and samples shape:  2017-04-07 01:12:00 (40, 84)
13
Current time and samples shape:  2017-04-07 01:13:00 (40, 84)
14
Current time and samples shape:  2017-04-07 01:14:00 (40, 84)
15
Current time and samples shape:  2017-04-07 01:15:00 (40, 84)
16
Current time and samples shape:  2017-04-07 01:16:00 (40, 84)
17
Current time and samples shape:  2017-04-07 01:17:00 (40, 84)
18
Current time and samples shape:  2017-04-07 01:18:00 (40, 84)
19
Current time and samples shape:  2017-04-07 01:19:00 (40, 84)
20
Current time and samples shape:  2017-04-07 01:20:00 (40, 84)
21
Current time and samples shape:  2017-04-07 01:21:00 (40, 84)
22
Current time and samples shape:  2017-04-07 01:22:00 (40, 84)
23
Current time and samples shape:  2017-04-07 01:23:00 (40, 84)
24
Current time and samples shape:  2017-04-07 01:24:00 (40, 84)
25
Current time and samples shape:  2017-04-07 01:25:00 (40, 84)
26
Current time and samples shape:  2017-04-07 01:26:00 (40, 84)
27
Current time and samples shape:  2017-04-07 01:27:00 (40, 84)
28
Current time and samples shape:  2017-04-07 01:28:00 (40, 84)
29
Current time and samples shape:  2017-04-07 01:29:00 (40, 84)
30
Current time and samples shape:  2017-04-07 01:30:00 (40, 84)
31
Current time and samples shape:  2017-04-07 01:31:00 (40, 84)
32
Current time and samples shape:  2017-04-07 01:32:00 (40, 84)
33
Current time and samples shape:  2017-04-07 01:33:00 (40, 84)
34
Current time and samples shape:  2017-04-07 01:34:00 (40, 84)
35
Current time and samples shape:  2017-04-07 01:35:00 (40, 84)
36
Current time and samples shape:  2017-04-07 01:36:00 (40, 84)
37
Current time and samples shape:  2017-04-07 01:37:00 (40, 84)
38
Current time and samples shape:  2017-04-07 01:38:00 (40, 84)
39
Current time and samples shape:  2017-04-07 01:39:00 (40, 84)
40
Current time and samples shape:  2017-04-07 01:40:00 (40, 84)
41
Current time and samples shape:  2017-04-07 01:41:00 (40, 84)
42
Current time and samples shape:  2017-04-07 01:42:00 (40, 84)
43
Current time and samples shape:  2017-04-07 01:43:00 (40, 84)
44
Current time and samples shape:  2017-04-07 01:44:00 (40, 84)
45
Current time and samples shape:  2017-04-07 01:45:00 (40, 84)
46
Current time and samples shape:  2017-04-07 01:46:00 (40, 84)
47
Current time and samples shape:  2017-04-07 01:47:00 (40, 84)
48
Current time and samples shape:  2017-04-07 01:48:00 (40, 84)
49
Current time and samples shape:  2017-04-07 01:49:00 (40, 84)
50
Current time and samples shape:  2017-04-07 01:50:00 (40, 84)
51
Current time and samples shape:  2017-04-07 01:51:00 (40, 84)
52
Current time and samples shape:  2017-04-07 01:52:00 (40, 84)
53
Current time and samples shape:  2017-04-07 01:53:00 (40, 84)
54
Current time and samples shape:  2017-04-07 01:54:00 (40, 84)
55
Current time and samples shape:  2017-04-07 01:55:00 (40, 84)
56
Current time and samples shape:  2017-04-07 01:56:00 (40, 84)
57
Current time and samples shape:  2017-04-07 01:57:00 (40, 84)
58
Current time and samples shape:  2017-04-07 01:58:00 (40, 84)
59
Current time and samples shape:  2017-04-07 01:59:00 (40, 84)
60
Current time and samples shape:  2017-04-07 02:00:00 (40, 84)
61
Current time and samples shape:  2017-04-07 02:01:00 (40, 84)
62
Current time and samples shape:  2017-04-07 02:02:00 (40, 84)
63
Current time and samples shape:  2017-04-07 02:03:00 (40, 84)
64
Current time and samples shape:  2017-04-07 02:04:00 (40, 84)
65
Current time and samples shape:  2017-04-07 02:05:00 (40, 84)
66
Current time and samples shape:  2017-04-07 02:06:00 (40, 84)
67
Current time and samples shape:  2017-04-07 02:07:00 (40, 84)
68
Current time and samples shape:  2017-04-07 02:08:00 (40, 84)
69
Current time and samples shape:  2017-04-07 02:09:00 (40, 84)
70
Current time and samples shape:  2017-04-07 02:10:00 (40, 84)
71
Current time and samples shape:  2017-04-07 02:11:00 (40, 84)
72
Current time and samples shape:  2017-04-07 02:12:00 (40, 84)
73
Current time and samples shape:  2017-04-07 02:13:00 (40, 84)
74
Current time and samples shape:  2017-04-07 02:14:00 (40, 84)
75
Current time and samples shape:  2017-04-07 02:15:00 (40, 84)
76
Current time and samples shape:  2017-04-07 02:16:00 (40, 84)
77
Current time and samples shape:  2017-04-07 02:17:00 (40, 84)
78
Current time and samples shape:  2017-04-07 02:18:00 (40, 84)
79
Current time and samples shape:  2017-04-07 02:19:00 (40, 84)
80
Current time and samples shape:  2017-04-07 02:20:00 (40, 84)
81
Current time and samples shape:  2017-04-07 02:21:00 (40, 84)
82
Current time and samples shape:  2017-04-07 02:22:00 (40, 84)
83
Current time and samples shape:  2017-04-07 02:23:00 (40, 84)
84
Current time and samples shape:  2017-04-07 02:24:00 (40, 84)
85
Current time and samples shape:  2017-04-07 02:25:00 (40, 84)
86
Current time and samples shape:  2017-04-07 02:26:00 (40, 84)
87
Current time and samples shape:  2017-04-07 02:27:00 (40, 84)
88
Current time and samples shape:  2017-04-07 02:28:00 (40, 84)
89
Current time and samples shape:  2017-04-07 02:29:00 (40, 84)
90
Current time and samples shape:  2017-04-07 02:30:00 (40, 84)
91
Current time and samples shape:  2017-04-07 02:31:00 (40, 84)
92
Current time and samples shape:  2017-04-07 02:32:00 (40, 84)
93
Current time and samples shape:  2017-04-07 02:33:00 (40, 84)
94
Current time and samples shape:  2017-04-07 02:34:00 (40, 84)
95
Current time and samples shape:  2017-04-07 02:35:00 (40, 84)
96
Current time and samples shape:  2017-04-07 02:36:00 (40, 84)
97
Current time and samples shape:  2017-04-07 02:37:00 (40, 84)
98
Current time and samples shape:  2017-04-07 02:38:00 (40, 84)
99
Current time and samples shape:  2017-04-07 02:39:00 (40, 84)
100
Current time and samples shape:  2017-04-07 02:40:00 (40, 84)
101
Current time and samples shape:  2017-04-07 02:41:00 (40, 84)
102
Current time and samples shape:  2017-04-07 02:42:00 (40, 84)
103
Current time and samples shape:  2017-04-07 02:43:00 (40, 84)
104
Current time and samples shape:  2017-04-07 02:44:00 (40, 84)
105
Current time and samples shape:  2017-04-07 02:45:00 (40, 84)
106
Current time and samples shape:  2017-04-07 02:46:00 (40, 84)
107
Current time and samples shape:  2017-04-07 02:47:00 (40, 84)
108
Current time and samples shape:  2017-04-07 02:48:00 (40, 84)
109
Current time and samples shape:  2017-04-07 02:49:00 (40, 84)
110
Current time and samples shape:  2017-04-07 02:50:00 (40, 84)
111
Current time and samples shape:  2017-04-07 02:51:00 (40, 84)
112
Current time and samples shape:  2017-04-07 02:52:00 (40, 84)
113
Current time and samples shape:  2017-04-07 02:53:00 (40, 84)
114
Current time and samples shape:  2017-04-07 02:54:00 (40, 84)
115
Current time and samples shape:  2017-04-07 02:55:00 (40, 84)
116
Current time and samples shape:  2017-04-07 02:56:00 (40, 84)
117
Current time and samples shape:  2017-04-07 02:57:00 (40, 84)
118
Current time and samples shape:  2017-04-07 02:58:00 (40, 84)
119
Current time and samples shape:  2017-04-07 02:59:00 (40, 84)
120
Current time and samples shape:  2017-04-07 03:00:00 (40, 84)
121
Current time and samples shape:  2017-04-07 03:01:00 (40, 84)
122
Current time and samples shape:  2017-04-07 03:02:00 (40, 84)
123
Current time and samples shape:  2017-04-07 03:03:00 (40, 84)
124
Current time and samples shape:  2017-04-07 03:04:00 (40, 84)
125
Current time and samples shape:  2017-04-07 03:05:00 (40, 84)
126
Current time and samples shape:  2017-04-07 03:06:00 (40, 84)
127

Current time and samples shape:  2017-04-07 03:07:00 (40, 84)
128
Current time and samples shape:  2017-04-07 03:08:00 (40, 84)
129
Current time and samples shape:  2017-04-07 03:09:00 (40, 84)
130
Current time and samples shape:  2017-04-07 03:10:00 (40, 84)
131
Current time and samples shape:  2017-04-07 03:11:00 (40, 84)
132
Current time and samples shape:  2017-04-07 03:12:00 (40, 84)
133
Current time and samples shape:  2017-04-07 03:13:00 (40, 84)
134
Current time and samples shape:  2017-04-07 03:14:00 (40, 84)
135
Current time and samples shape:  2017-04-07 03:15:00 (40, 84)
136
Current time and samples shape:  2017-04-07 03:16:00 (40, 84)
137
Current time and samples shape:  2017-04-07 03:17:00 (40, 84)
138
Current time and samples shape:  2017-04-07 03:18:00 (40, 84)
139
Current time and samples shape:  2017-04-07 03:19:00 (40, 84)
140
Current time and samples shape:  2017-04-07 03:20:00 (40, 84)
141
Current time and samples shape:  2017-04-07 03:21:00 (40, 84)
142
Current time and samples shape:  2017-04-07 03:22:00 (40, 84)
143
Current time and samples shape:  2017-04-07 03:23:00 (40, 84)
144
Current time and samples shape:  2017-04-07 03:24:00 (40, 84)
145
Current time and samples shape:  2017-04-07 03:25:00 (40, 84)
146
Current time and samples shape:  2017-04-07 03:26:00 (40, 84)
147
Current time and samples shape:  2017-04-07 03:27:00 (40, 84)
148
Current time and samples shape:  2017-04-07 03:28:00 (40, 84)
149
Current time and samples shape:  2017-04-07 03:29:00 (40, 84)
150
Current time and samples shape:  2017-04-07 03:30:00 (40, 84)
151
Current time and samples shape:  2017-04-07 03:31:00 (40, 84)
152
Current time and samples shape:  2017-04-07 03:32:00 (40, 84)
153
Current time and samples shape:  2017-04-07 03:33:00 (40, 84)
154
Current time and samples shape:  2017-04-07 03:34:00 (40, 84)
155
Current time and samples shape:  2017-04-07 03:35:00 (40, 84)
156
Current time and samples shape:  2017-04-07 03:36:00 (40, 84)
157
Current time and samples shape:  2017-04-07 03:37:00 (40, 84)
158
Current time and samples shape:  2017-04-07 03:38:00 (40, 84)
159
Current time and samples shape:  2017-04-07 03:39:00 (40, 84)
160
Current time and samples shape:  2017-04-07 03:40:00 (40, 84)
161
Current time and samples shape:  2017-04-07 03:41:00 (40, 84)
162
Current time and samples shape:  2017-04-07 03:42:00 (40, 84)
163
Current time and samples shape:  2017-04-07 03:43:00 (40, 84)
164
Current time and samples shape:  2017-04-07 03:44:00 (40, 84)
165
Current time and samples shape:  2017-04-07 03:45:00 (40, 84)
166
Current time and samples shape:  2017-04-07 03:46:00 (40, 84)
167
Current time and samples shape:  2017-04-07 03:47:00 (40, 84)
168
Current time and samples shape:  2017-04-07 03:48:00 (40, 84)
169
Current time and samples shape:  2017-04-07 03:49:00 (40, 84)
170
Current time and samples shape:  2017-04-07 03:50:00 (40, 84)
171
Current time and samples shape:  2017-04-07 03:51:00 (40, 84)
172
Current time and samples shape:  2017-04-07 03:52:00 (40, 84)
173
Current time and samples shape:  2017-04-07 03:53:00 (40, 84)
174
Current time and samples shape:  2017-04-07 03:54:00 (40, 84)
175
Current time and samples shape:  2017-04-07 03:55:00 (40, 84)
176
Current time and samples shape:  2017-04-07 03:56:00 (40, 84)
177
Current time and samples shape:  2017-04-07 03:57:00 (40, 84)
178
Current time and samples shape:  2017-04-07 03:58:00 (40, 84)
179
Current time and samples shape:  2017-04-07 03:59:00 (40, 84)
180
Current time and samples shape:  2017-04-07 04:00:00 (40, 84)
181
Current time and samples shape:  2017-04-07 04:01:00 (40, 84)
182
Current time and samples shape:  2017-04-07 04:02:00 (40, 84)
183
Current time and samples shape:  2017-04-07 04:03:00 (40, 84)
184
Current time and samples shape:  2017-04-07 04:04:00 (40, 84)
185
Current time and samples shape:  2017-04-07 04:05:00 (40, 84)
186
Current time and samples shape:  2017-04-07 04:06:00 (40, 84)
187
Current time and samples shape:  2017-04-07 04:07:00 (40, 84)
188
Current time and samples shape:  2017-04-07 04:08:00 (40, 84)
189
Current time and samples shape:  2017-04-07 04:09:00 (40, 84)
190
Current time and samples shape:  2017-04-07 04:10:00 (40, 84)
191
Current time and samples shape:  2017-04-07 04:11:00 (40, 84)
192
Current time and samples shape:  2017-04-07 04:12:00 (40, 84)
193
Current time and samples shape:  2017-04-07 04:13:00 (40, 84)
194
Current time and samples shape:  2017-04-07 04:14:00 (40, 84)
195
Current time and samples shape:  2017-04-07 04:15:00 (40, 84)
196
Current time and samples shape:  2017-04-07 04:16:00 (40, 84)
197
Current time and samples shape:  2017-04-07 04:17:00 (40, 84)
198
Current time and samples shape:  2017-04-07 04:18:00 (40, 84)
199
Current time and samples shape:  2017-04-07 04:19:00 (40, 84)
200
Current time and samples shape:  2017-04-07 04:20:00 (40, 84)
201
Current time and samples shape:  2017-04-07 04:21:00 (40, 84)
202
Current time and samples shape:  2017-04-07 04:22:00 (40, 84)
203
Current time and samples shape:  2017-04-07 04:23:00 (40, 84)
204
Current time and samples shape:  2017-04-07 04:24:00 (40, 84)
205
Current time and samples shape:  2017-04-07 04:25:00 (40, 84)
206
Current time and samples shape:  2017-04-07 04:26:00 (40, 84)
207
Current time and samples shape:  2017-04-07 04:27:00 (40, 84)
208
Current time and samples shape:  2017-04-07 04:28:00 (40, 84)
209
Current time and samples shape:  2017-04-07 04:29:00 (40, 84)
210
Current time and samples shape:  2017-04-07 04:30:00 (40, 84)
211
Current time and samples shape:  2017-04-07 04:31:00 (40, 84)
212
Current time and samples shape:  2017-04-07 04:32:00 (40, 84)
213
Current time and samples shape:  2017-04-07 04:33:00 (40, 84)
214
Current time and samples shape:  2017-04-07 04:34:00 (40, 84)
215
Current time and samples shape:  2017-04-07 04:35:00 (40, 84)
216
Current time and samples shape:  2017-04-07 04:36:00 (40, 84)
217
Current time and samples shape:  2017-04-07 04:37:00 (40, 84)
218
Current time and samples shape:  2017-04-07 04:38:00 (40, 84)
219
Current time and samples shape:  2017-04-07 04:39:00 (40, 84)
220
Current time and samples shape:  2017-04-07 04:40:00 (40, 84)
221
Current time and samples shape:  2017-04-07 04:41:00 (40, 84)
222
Current time and samples shape:  2017-04-07 04:42:00 (40, 84)
223
Current time and samples shape:  2017-04-07 04:43:00 (40, 84)
224
Current time and samples shape:  2017-04-07 04:44:00 (40, 84)
225
Current time and samples shape:  2017-04-07 04:45:00 (40, 84)
226
Current time and samples shape:  2017-04-07 04:46:00 (40, 84)
227
Current time and samples shape:  2017-04-07 04:47:00 (40, 84)
228
Current time and samples shape:  2017-04-07 04:48:00 (40, 84)
229
Current time and samples shape:  2017-04-07 04:49:00 (40, 84)
230
Current time and samples shape:  2017-04-07 04:50:00 (40, 84)
231
Current time and samples shape:  2017-04-07 04:51:00 (40, 84)
232
Current time and samples shape:  2017-04-07 04:52:00 (40, 84)
233
Current time and samples shape:  2017-04-07 04:53:00 (40, 84)
234
Current time and samples shape:  2017-04-07 04:54:00 (40, 84)
235
Current time and samples shape:  2017-04-07 04:55:00 (40, 84)
236
Current time and samples shape:  2017-04-07 04:56:00 (40, 84)
237
Current time and samples shape:  2017-04-07 04:57:00 (40, 84)
238
Current time and samples shape:  2017-04-07 04:58:00 (40, 84)
239
Current time and samples shape:  2017-04-07 04:59:00 (40, 84)
240
Current time and samples shape:  2017-04-07 05:00:00 (40, 84)
241
Current time and samples shape:  2017-04-07 08:53:00 (40, 84)
242
Current time and samples shape:  2017-04-07 08:55:00 (40, 84)
243
Current time and samples shape:  2017-04-07 08:56:00 (40, 84)
244
Current time and samples shape:  2017-04-07 08:57:00 (40, 84)
245
Current time and samples shape:  2017-04-07 08:58:00 (40, 84)
246
Current time and samples shape:  2017-04-07 08:59:00 (40, 84)
247
Current time and samples shape:  2017-04-07 09:00:00 (40, 84)
248
Current time and samples shape:  2017-04-07 09:01:00 (40, 84)
249
Current time and samples shape:  2017-04-07 09:02:00 (40, 84)
250
Current time and samples shape:  2017-04-07 09:03:00 (40, 84)
251
Current time and samples shape:  2017-04-07 09:04:00 (40, 84)

252
Current time and samples shape:  2017-04-07 09:05:00 (40, 84)
253
Current time and samples shape:  2017-04-07 09:06:00 (40, 84)
254
Current time and samples shape:  2017-04-07 09:07:00 (40, 84)
255
Current time and samples shape:  2017-04-07 09:08:00 (40, 84)
256
Current time and samples shape:  2017-04-07 09:09:00 (40, 84)
257
Current time and samples shape:  2017-04-07 09:10:00 (40, 84)
258
Current time and samples shape:  2017-04-07 09:11:00 (40, 84)
259
Current time and samples shape:  2017-04-07 09:12:00 (40, 84)
260
Current time and samples shape:  2017-04-07 09:13:00 (40, 84)
261
Current time and samples shape:  2017-04-07 09:14:00 (40, 84)
262
Current time and samples shape:  2017-04-07 09:15:00 (40, 84)
263
Current time and samples shape:  2017-04-07 09:16:00 (40, 84)
264
Current time and samples shape:  2017-04-07 09:17:00 (40, 84)
265
Current time and samples shape:  2017-04-07 09:18:00 (40, 84)
266
Current time and samples shape:  2017-04-07 09:19:00 (40, 84)
267
Current time and samples shape:  2017-04-07 09:20:00 (40, 84)
268
Current time and samples shape:  2017-04-07 09:21:00 (40, 84)
269
Current time and samples shape:  2017-04-07 09:22:00 (40, 84)
270
Current time and samples shape:  2017-04-07 09:23:00 (40, 84)
271
Current time and samples shape:  2017-04-07 09:24:00 (40, 84)
272
Current time and samples shape:  2017-04-07 09:25:00 (40, 84)
273
Current time and samples shape:  2017-04-07 09:26:00 (40, 84)
274
Current time and samples shape:  2017-04-07 09:27:00 (40, 84)
275
Current time and samples shape:  2017-04-07 09:28:00 (40, 84)
276
Current time and samples shape:  2017-04-07 09:29:00 (40, 84)
277
Current time and samples shape:  2017-04-07 09:30:00 (40, 84)
278
Current time and samples shape:  2017-04-07 09:31:00 (40, 84)
279
Current time and samples shape:  2017-04-07 09:32:00 (40, 84)
280
Current time and samples shape:  2017-04-07 09:33:00 (40, 84)
281
Current time and samples shape:  2017-04-07 09:34:00 (40, 84)
282
Current time and samples shape:  2017-04-07 09:35:00 (40, 84)
283
Current time and samples shape:  2017-04-07 09:36:00 (40, 84)
284
Current time and samples shape:  2017-04-07 09:37:00 (40, 84)
285
Current time and samples shape:  2017-04-07 09:38:00 (40, 84)
286
Current time and samples shape:  2017-04-07 09:39:00 (40, 84)
287
Current time and samples shape:  2017-04-07 09:40:00 (40, 84)
288
Current time and samples shape:  2017-04-07 09:41:00 (40, 84)
289
Current time and samples shape:  2017-04-07 09:42:00 (40, 84)
290
Current time and samples shape:  2017-04-07 09:43:00 (40, 84)
291
Current time and samples shape:  2017-04-07 09:44:00 (40, 84)
292
Current time and samples shape:  2017-04-07 09:45:00 (40, 84)
293
Current time and samples shape:  2017-04-07 09:46:00 (40, 84)
294
Current time and samples shape:  2017-04-07 09:47:00 (40, 84)
295
Current time and samples shape:  2017-04-07 09:48:00 (40, 84)
296
Current time and samples shape:  2017-04-07 09:49:00 (40, 84)
297
Current time and samples shape:  2017-04-07 09:50:00 (40, 84)
298
Current time and samples shape:  2017-04-07 09:51:00 (40, 84)
299
Current time and samples shape:  2017-04-07 09:52:00 (40, 84)
300
Current time and samples shape:  2017-04-07 09:53:00 (40, 84)
301
Current time and samples shape:  2017-04-07 09:54:00 (40, 84)
302
Current time and samples shape:  2017-04-07 09:55:00 (40, 84)
303
Current time and samples shape:  2017-04-07 09:56:00 (40, 84)
304
Current time and samples shape:  2017-04-07 09:57:00 (40, 84)
305
Current time and samples shape:  2017-04-07 09:58:00 (40, 84)
306
Current time and samples shape:  2017-04-07 09:59:00 (40, 84)
307
Current time and samples shape:  2017-04-07 10:00:00 (40, 84)
308
Current time and samples shape:  2017-04-07 10:01:00 (40, 84)
309
Current time and samples shape:  2017-04-07 10:02:00 (40, 84)
310
Current time and samples shape:  2017-04-07 10:03:00 (40, 84)
311
Current time and samples shape:  2017-04-07 10:04:00 (40, 84)
312
Current time and samples shape:  2017-04-07 10:05:00 (40, 84)
313
Current time and samples shape:  2017-04-07 10:06:00 (40, 84)
314
Current time and samples shape:  2017-04-07 10:07:00 (40, 84)
315
Current time and samples shape:  2017-04-07 10:08:00 (40, 84)
316
Current time and samples shape:  2017-04-07 10:09:00 (40, 84)
317
Current time and samples shape:  2017-04-07 10:10:00 (40, 84)
318
Current time and samples shape:  2017-04-07 10:11:00 (40, 84)
319
Current time and samples shape:  2017-04-07 10:12:00 (40, 84)
320
Current time and samples shape:  2017-04-07 10:13:00 (40, 84)
321
Current time and samples shape:  2017-04-07 10:14:00 (40, 84)
322
Current time and samples shape:  2017-04-07 10:15:00 (40, 84)
323
Current time and samples shape:  2017-04-07 10:16:00 (40, 84)
324
Current time and samples shape:  2017-04-07 10:17:00 (40, 84)
325
Current time and samples shape:  2017-04-07 10:18:00 (40, 84)
326
Current time and samples shape:  2017-04-07 10:19:00 (40, 84)
327
Current time and samples shape:  2017-04-07 10:20:00 (40, 84)
328
Current time and samples shape:  2017-04-07 10:21:00 (40, 84)
329
Current time and samples shape:  2017-04-07 10:22:00 (40, 84)
330
Current time and samples shape:  2017-04-07 10:23:00 (40, 84)
331
Current time and samples shape:  2017-04-07 10:24:00 (40, 84)
332
Current time and samples shape:  2017-04-07 10:25:00 (40, 84)
333
Current time and samples shape:  2017-04-07 10:26:00 (40, 84)
334
Current time and samples shape:  2017-04-07 10:27:00 (40, 84)
335
Current time and samples shape:  2017-04-07 10:28:00 (40, 84)
336
Current time and samples shape:  2017-04-07 10:29:00 (40, 84)
337
Current time and samples shape:  2017-04-07 10:30:00 (40, 84)
338
Current time and samples shape:  2017-04-07 10:31:00 (40, 84)
339
Current time and samples shape:  2017-04-07 10:32:00 (40, 84)
340
Current time and samples shape:  2017-04-07 10:33:00 (40, 84)
341
Current time and samples shape:  2017-04-07 10:34:00 (40, 84)
342
Current time and samples shape:  2017-04-07 10:35:00 (40, 84)
343
Current time and samples shape:  2017-04-07 10:36:00 (40, 84)
344
Current time and samples shape:  2017-04-07 10:37:00 (40, 84)
345
Current time and samples shape:  2017-04-07 10:38:00 (40, 84)
346
Current time and samples shape:  2017-04-07 10:39:00 (40, 84)
347
Current time and samples shape:  2017-04-07 10:40:00 (40, 84)
348
Current time and samples shape:  2017-04-07 10:41:00 (40, 84)
349
Current time and samples shape:  2017-04-07 10:42:00 (40, 84)
350
Current time and samples shape:  2017-04-07 10:43:00 (40, 84)
351
Current time and samples shape:  2017-04-07 10:44:00 (40, 84)
352
Current time and samples shape:  2017-04-07 10:45:00 (40, 84)
353
Current time and samples shape:  2017-04-07 10:46:00 (40, 84)
354
Current time and samples shape:  2017-04-07 10:47:00 (40, 84)
355
Current time and samples shape:  2017-04-07 10:48:00 (40, 84)
356
Current time and samples shape:  2017-04-07 10:49:00 (40, 84)
357
Current time and samples shape:  2017-04-07 10:50:00 (40, 84)
358
Current time and samples shape:  2017-04-07 10:51:00 (40, 84)
359
Current time and samples shape:  2017-04-07 10:52:00 (40, 84)
360
Current time and samples shape:  2017-04-07 10:53:00 (40, 84)
361
Current time and samples shape:  2017-04-07 10:54:00 (40, 84)
362
Current time and samples shape:  2017-04-07 10:55:00 (40, 84)
363
Current time and samples shape:  2017-04-07 10:56:00 (40, 84)
364
Current time and samples shape:  2017-04-07 10:57:00 (40, 84)
365
Current time and samples shape:  2017-04-07 10:58:00 (40, 84)
366
Current time and samples shape:  2017-04-07 10:59:00 (40, 84)
367
Current time and samples shape:  2017-04-07 11:00:00 (40, 84)
368
Current time and samples shape:  2017-04-07 11:01:00 (40, 84)
369
Current time and samples shape:  2017-04-07 11:02:00 (40, 84)
370
Current time and samples shape:  2017-04-07 11:03:00 (40, 84)
371
Current time and samples shape:  2017-04-07 11:04:00 (40, 84)
372
Current time and samples shape:  2017-04-07 11:05:00 (40, 84)
373
Current time and samples shape:  2017-04-07 11:06:00 (40, 84)
374
Current time and samples shape:  2017-04-07 11:07:00 (40, 84)
375
Current time and samples shape:  2017-04-07 11:08:00 (40, 84)
376
Current time and samples shape:  2017-04-07 11:09:00 (40, 84)

377
Current time and samples shape:  2017-04-07 11:10:00 (40, 84)
378
Current time and samples shape:  2017-04-07 11:11:00 (40, 84)
379
Current time and samples shape:  2017-04-07 11:12:00 (40, 84)
380
Current time and samples shape:  2017-04-07 11:13:00 (40, 84)
381
Current time and samples shape:  2017-04-07 11:14:00 (40, 84)
382
Current time and samples shape:  2017-04-07 11:15:00 (40, 84)
383
Current time and samples shape:  2017-04-07 11:16:00 (40, 84)
384
Current time and samples shape:  2017-04-07 11:17:00 (40, 84)
385
Current time and samples shape:  2017-04-07 11:18:00 (40, 84)
386
Current time and samples shape:  2017-04-07 11:19:00 (40, 84)
387
Current time and samples shape:  2017-04-07 11:20:00 (40, 84)
388
Current time and samples shape:  2017-04-07 11:21:00 (40, 84)
389
Current time and samples shape:  2017-04-07 11:22:00 (40, 84)
390
Current time and samples shape:  2017-04-07 11:23:00 (40, 84)
391
Current time and samples shape:  2017-04-07 11:24:00 (40, 84)
392
Current time and samples shape:  2017-04-07 11:25:00 (40, 84)
393
Current time and samples shape:  2017-04-07 11:26:00 (40, 84)
394
Current time and samples shape:  2017-04-07 11:27:00 (40, 84)
395
Current time and samples shape:  2017-04-07 11:28:00 (40, 84)
396
Current time and samples shape:  2017-04-07 11:29:00 (40, 84)
397
Current time and samples shape:  2017-04-07 11:30:00 (40, 84)
398
Current time and samples shape:  2017-04-07 11:31:00 (40, 84)
399
Current time and samples shape:  2017-04-07 11:32:00 (40, 84)
400
Current time and samples shape:  2017-04-07 11:33:00 (40, 84)
401
Current time and samples shape:  2017-04-07 11:34:00 (40, 84)
402
Current time and samples shape:  2017-04-07 11:35:00 (40, 84)
403
Current time and samples shape:  2017-04-07 11:36:00 (40, 84)
404
Current time and samples shape:  2017-04-07 11:37:00 (40, 84)
405
Current time and samples shape:  2017-04-07 11:38:00 (40, 84)
406
Current time and samples shape:  2017-04-07 11:39:00 (40, 84)
407
Current time and samples shape:  2017-04-07 11:40:00 (40, 84)
408
Current time and samples shape:  2017-04-07 11:41:00 (40, 84)
409
Current time and samples shape:  2017-04-07 11:42:00 (40, 84)
410
Current time and samples shape:  2017-04-07 11:43:00 (40, 84)
411
Current time and samples shape:  2017-04-07 11:44:00 (40, 84)
412
Current time and samples shape:  2017-04-07 11:45:00 (40, 84)
413
Current time and samples shape:  2017-04-07 11:46:00 (40, 84)
414
Current time and samples shape:  2017-04-07 11:47:00 (40, 84)
415
Current time and samples shape:  2017-04-07 11:48:00 (40, 84)
416
Current time and samples shape:  2017-04-07 11:49:00 (40, 84)
417
Current time and samples shape:  2017-04-07 11:50:00 (40, 84)
418
Current time and samples shape:  2017-04-07 11:51:00 (40, 84)
419
Current time and samples shape:  2017-04-07 11:52:00 (40, 84)
420
Current time and samples shape:  2017-04-07 11:53:00 (40, 84)
421
Current time and samples shape:  2017-04-07 11:54:00 (40, 84)
422
Current time and samples shape:  2017-04-07 11:55:00 (40, 84)
423
Current time and samples shape:  2017-04-07 11:56:00 (40, 84)
424
Current time and samples shape:  2017-04-07 11:57:00 (40, 84)
425
Current time and samples shape:  2017-04-07 11:58:00 (40, 84)
426
Current time and samples shape:  2017-04-07 11:59:00 (40, 84)
427
Current time and samples shape:  2017-04-07 12:00:00 (40, 84)
428
Current time and samples shape:  2017-04-07 12:01:00 (40, 84)
429
Current time and samples shape:  2017-04-07 12:02:00 (40, 84)
430
Current time and samples shape:  2017-04-07 12:03:00 (40, 84)
431
Current time and samples shape:  2017-04-07 12:04:00 (40, 84)
432
Current time and samples shape:  2017-04-07 12:05:00 (40, 84)
433
Current time and samples shape:  2017-04-07 12:06:00 (40, 84)
434
Current time and samples shape:  2017-04-07 12:07:00 (40, 84)
435
Current time and samples shape:  2017-04-07 12:08:00 (40, 84)
436
Current time and samples shape:  2017-04-07 12:09:00 (40, 84)
437
Current time and samples shape:  2017-04-07 12:10:00 (40, 84)
438
Current time and samples shape:  2017-04-07 12:11:00 (40, 84)
439
Current time and samples shape:  2017-04-07 12:12:00 (40, 84)
440
Current time and samples shape:  2017-04-07 12:13:00 (40, 84)
441
Current time and samples shape:  2017-04-07 12:14:00 (40, 84)
442
Current time and samples shape:  2017-04-07 12:15:00 (40, 84)
443
Current time and samples shape:  2017-04-07 12:16:00 (40, 84)
444
Current time and samples shape:  2017-04-07 12:17:00 (40, 84)
445
Current time and samples shape:  2017-04-07 12:18:00 (40, 84)
446
Current time and samples shape:  2017-04-07 12:19:00 (40, 84)
447
Current time and samples shape:  2017-04-07 12:20:00 (40, 84)
448
Current time and samples shape:  2017-04-07 12:21:00 (40, 84)
449
Current time and samples shape:  2017-04-07 12:22:00 (40, 84)
450
Current time and samples shape:  2017-04-07 12:23:00 (40, 84)
451
Current time and samples shape:  2017-04-07 12:24:00 (40, 84)
452
Current time and samples shape:  2017-04-07 12:25:00 (40, 84)
453
Current time and samples shape:  2017-04-07 12:26:00 (40, 84)
454
Current time and samples shape:  2017-04-07 12:27:00 (40, 84)
455
Current time and samples shape:  2017-04-07 12:28:00 (40, 84)
456
Current time and samples shape:  2017-04-07 12:29:00 (40, 84)
457
Current time and samples shape:  2017-04-07 12:30:00 (40, 84)
458
Current time and samples shape:  2017-04-07 12:31:00 (40, 84)
459
Current time and samples shape:  2017-04-07 12:32:00 (40, 84)
460
Current time and samples shape:  2017-04-07 12:33:00 (40, 84)
461
Current time and samples shape:  2017-04-07 12:34:00 (40, 84)
462
Current time and samples shape:  2017-04-07 12:35:00 (40, 84)
463
Current time and samples shape:  2017-04-07 12:36:00 (40, 84)
464
Current time and samples shape:  2017-04-07 12:37:00 (40, 84)
465
Current time and samples shape:  2017-04-07 12:38:00 (40, 84)
466
Current time and samples shape:  2017-04-07 12:39:00 (40, 84)
467
Current time and samples shape:  2017-04-07 12:40:00 (40, 84)
468
Current time and samples shape:  2017-04-07 12:41:00 (40, 84)
469
Current time and samples shape:  2017-04-07 12:42:00 (40, 84)
470
Current time and samples shape:  2017-04-07 12:43:00 (40, 84)
471
Current time and samples shape:  2017-04-07 12:44:00 (40, 84)
472
Current time and samples shape:  2017-04-07 12:45:00 (40, 84)
473
Current time and samples shape:  2017-04-07 12:46:00 (40, 84)
474
Current time and samples shape:  2017-04-07 12:47:00 (40, 84)
475
Current time and samples shape:  2017-04-07 12:48:00 (40, 84)
476
Current time and samples shape:  2017-04-07 12:49:00 (40, 84)
477
Current time and samples shape:  2017-04-07 12:50:00 (40, 84)
478
Current time and samples shape:  2017-04-07 12:51:00 (40, 84)
479
Current time and samples shape:  2017-04-07 12:52:00 (40, 84)
480
Current time and samples shape:  2017-04-07 12:53:00 (40, 84)
481
Current time and samples shape:  2017-04-07 12:54:00 (40, 84)
482
Current time and samples shape:  2017-04-07 12:55:00 (40, 84)
483
Current time and samples shape:  2017-04-07 12:56:00 (40, 84)
484
Current time and samples shape:  2017-04-07 12:57:00 (40, 84)
485
Current time and samples shape:  2017-04-07 12:58:00 (40, 84)
486
Current time and samples shape:  2017-04-07 12:59:00 (40, 84)

In [8]:
with open(r'saves\tuesday_graphs_20_0_5.pickle', 'wb') as handle:
    pickle.dump((all_graphs, labels, label_counts), handle, protocol=pickle.HIGHEST_PROTOCOL)

In [20]:
with open(r'saves\tuesday_graphs_20_0_5.pickle', 'rb') as handle:
    all_graphs, labels, label_counts = pickle.load(handle)

In [21]:
all_graphs.shape

(487, 84, 84)

In [22]:
np.unique(labels, return_counts=True)

(array(['BENIGN', 'Empty', 'FTP-Patator', 'SSH-Patator'], dtype='<U11'),
 array([359,   1,  64,  63], dtype=int64))

In [77]:
import pandas as pd
import numpy as np
import networkx as nx
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

from sklearn import model_selection
from IPython.display import display, HTML

import stellargraph as sg
from stellargraph.mapper import PaddedGraphGenerator
from stellargraph.layer import GCNSupervisedGraphClassification

from tensorflow.keras import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import binary_crossentropy
from tensorflow.keras.callbacks import EarlyStopping

In [71]:
import importlib, src
import src.network_embedding

importlib.reload(src.network_embedding)
from src.network_embedding import*

In [72]:
nn = 100
graphs, graph_labels = graph_arrays_to_stellargraphs_labels(all_graphs[:nn,:,:], names, labels[:nn])
print(graphs[-1].info())

StellarGraph: Undirected multigraph
 Nodes: 84, Edges: 3570

 Node types:
  default: [84]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [3570]
        Weights: range=[0, 1], mean=0.107563, std=0.309871
        Features: none

In [73]:
summary = pd.DataFrame(
    [(g.number_of_nodes(), g.number_of_edges()) for g in graphs],
    columns=["nodes", "edges"],
)
summary.describe().round(1)

       nodes   edges
count  100.0   100.0
mean    84.0  3570.0
std      0.0     0.0
min     84.0  3570.0
25%     84.0  3570.0
50%     84.0  3570.0
75%     84.0  3570.0
max     84.0  3570.0

In [74]:
graph_labels.describe()

         label
count      100
unique       2
top     BENIGN
freq        69

In [78]:
generator = PaddedGraphGenerator(graphs=graphs)

RuntimeError: This StellarGraph has no numeric feature attributes for nodesNode features are required for machine learning

In [76]:
def create_graph_classification_model(generator):
    gc_model = GCNSupervisedGraphClassification(
        layer_sizes=[16, 16],
        activations=["relu", "relu"],
        generator=generator,
        dropout=0.5,
    )
    x_inp, x_out = gc_model.in_out_tensors()
    predictions = Dense(units=16, activation="relu")(x_out)
    predictions = Dense(units=8, activation="relu")(predictions)
    predictions = Dense(units=1, activation="sigmoid")(predictions)

    # Let's create the Keras model and prepare it for training
    model = Model(inputs=x_inp, outputs=predictions)
    model.compile(optimizer=Adam(0.005), loss=binary_crossentropy, metrics=["acc"])

    return model

In [ ]:
epochs = 200  # maximum number of training epochs
folds = 1 # 10  # the number of folds for k-fold cross validation
n_repeats = 1 # 5 # the number of repeats for repeated k-fold cross validation

es = EarlyStopping(
    monitor="val_loss", min_delta=0, patience=25, restore_best_weights=True
)

def train_fold(model, train_gen, test_gen, es, epochs):
    history = model.fit(
        train_gen, epochs=epochs, validation_data=test_gen, verbose=0, callbacks=[es],
    )
    # calculate performance on the test data and return along with history
    test_metrics = model.evaluate(test_gen, verbose=0)
    test_acc = test_metrics[model.metrics_names.index("acc")]

    return history, test_acc

def get_generators(train_index, test_index, graph_labels, batch_size):
    train_gen = generator.flow(
        train_index, targets=graph_labels.iloc[train_index].values, batch_size=batch_size
    )
    test_gen = generator.flow(
        test_index, targets=graph_labels.iloc[test_index].values, batch_size=batch_size
    )

    return train_gen, test_gen

Example Supervised

In [51]:
import pandas as pd
import os

import stellargraph as sg
from stellargraph.mapper import FullBatchNodeGenerator
from stellargraph.layer import GCN

from tensorflow.keras import layers, optimizers, losses, metrics, Model
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
%matplotlib inline

In [43]:
from stellargraph.datasets import Cora
import os

cora = Cora()
cora.download()

In [45]:
dataset = sg.datasets.Cora()
display(HTML(dataset.description))
G, node_subjects = dataset.load()

In [48]:
print(G.info())

StellarGraph: Undirected multigraph
 Nodes: 2708, Edges: 5429

 Node types:
  paper: [2708]
    Features: float32 vector, length 1433
    Edge types: paper-cites->paper

 Edge types:
    paper-cites->paper: [5429]
        Weights: all 1 (default)
        Features: none

In [49]:
node_subjects.value_counts().to_frame()

                        count
subject
Neural_Networks           818
Probabilistic_Methods     426
Genetic_Algorithms        418
Theory                    351
Case_Based                298
Reinforcement_Learning    217
Rule_Learning             180

In [52]:
train_subjects, test_subjects = model_selection.train_test_split(
    node_subjects, train_size=140, test_size=None, stratify=node_subjects
)
val_subjects, test_subjects = model_selection.train_test_split(
    test_subjects, train_size=500, test_size=None, stratify=test_subjects
)

In [53]:
train_subjects.value_counts().to_frame()

                        count
subject
Neural_Networks            42
Probabilistic_Methods      22
Genetic_Algorithms         22
Theory                     18
Case_Based                 16
Reinforcement_Learning     11
Rule_Learning               9

In [55]:
target_encoding = preprocessing.LabelBinarizer()

train_targets = target_encoding.fit_transform(train_subjects)
val_targets = target_encoding.transform(val_subjects)
test_targets = target_encoding.transform(test_subjects)

In [57]:
generator = FullBatchNodeGenerator(G, method="gcn")
train_gen = generator.flow(train_subjects.index, train_targets)

Using GCN (local pooling) filters...

In [59]:
train_gen

Risk Mean as Input

Covariance Matrix as Input

GNN

GAEN (Graph Auto Encoder Network)

Unsupervised

Results & Embedding